baseURL = "https://yeahcola.github.io/"
languageCode = "en-us"
title = "yeah"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "projects"
url = "/project"
weight = 3

[[menu.main]]
name = "photos"
url = "/photo"
weight = 4

[[menu.main]]
name = "about"
url = "/about"
weight = 5

[[menu.main]]
name = "tags"
url = "/tags"
weight = 6
